version: '3'
services:
  # mysql
  chatgpt-plus-mysql:
    image: mysql:8.0.33
    container_name: trender-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=yourpassword
    ports:
      - "3307:3306"
    volumes :
      - ./mysql/conf/my.cnf:/etc/mysql/my.cnf
      - ./mysql/data:/var/lib/mysql
      - ./mysql/logs:/var/log/mysql
      - ./mysql/init.d:/docker-entrypoint-initdb.d/
